In [23]:
from scipy.stats import chi2_contingency
import numpy as np
import scipy


coins = np.array([[0,1,2,3,4,5,6],[1,2,2,5,6,3,1]])

coins2 = np.array([[0,1,5,5,6,3,0],[1,2,2,5,6,3,1]])
print(coins)
print(coins2)

stats= chi2_contingency(coins)
stats2= chi2_contingency(coins2)
print(stats)
print(stats2)

[[0 1 2 3 4 5 6]
 [1 2 2 5 6 3 1]]
[[0 1 5 5 6 3 0]
 [1 2 2 5 6 3 1]]
Chi2ContingencyResult(statistic=6.284109977324263, pvalue=0.39212799969551393, dof=6, expected_freq=array([[0.51219512, 1.53658537, 2.04878049, 4.09756098, 5.12195122,
        4.09756098, 3.58536585],
       [0.48780488, 1.46341463, 1.95121951, 3.90243902, 4.87804878,
        3.90243902, 3.41463415]]))
Chi2ContingencyResult(statistic=3.6190476190476186, pvalue=0.7280694341350952, dof=6, expected_freq=array([[0.5, 1.5, 3.5, 5. , 6. , 3. , 0.5],
       [0.5, 1.5, 3.5, 5. , 6. , 3. , 0.5]]))


In [5]:
data=[ 2.4, 2.45, 2.47, 3.13, 2.92, 2.85, 2.05, 2.52, 2.94, 1.89, 1.94, 1.55, 2.12, 2.17, 3.06, 1.97, 2.23, 3.20, 2.24, 2.60]
data2=[ 2.59, 2.65, 2.55, 2.07, 2.61, 2.61, 2.54, 2.76, 2.37, 2.57]

(sum(data) + sum(data2))/30

2.467333333333334

TypeError: unsupported operand type(s) for -: 'list' and 'float'

In [23]:
data3=[ 2.4, 2.45, 2.47, 3.13, 2.92, 2.85, 2.05, 2.52, 2.94, 1.89, 1.94, 1.55, 2.12, 2.17, 3.06, 1.97, 2.23, 3.20, 2.24, 2.60, 2.59, 2.65, 2.55, 2.07, 2.61, 2.61, 2.54, 2.76, 2.37, 2.57]

s=0
for i in data3:
    s+=(i-2.467)**2
print(s)
s=math.sqrt(s/29)
    
print(s)

4.483390000000001
0.3931916265288642


In [10]:
import math

.39/math.sqrt(60)

0.050348783500696416